### ISSUE TITLE
Entities becoming unavailable

### ISSUE THREAD

**Issue by CarstenDennis** [weltmeyer/ha_sonnenbatterie#45]
Hey guys

Did your sonnen battery entities also become unavailable?

I currently see this:
![image](https://github.com/weltmeyer/ha_sonnenbatterie/assets/139639309/8382442e-d027-42d4-bed0-084a006b3775)

I did do a update to a newer home:assistant build - but after rolling back it was still the same - so I'm wondering if you guys see the same.

**Comment by CarstenDennis** [comment]
Thanks - that pointed me in the right direction:
02/17/2024
04:38:55 PM
Traceback (most recent call last):
02/17/2024
04:38:55 PM
  File "/usr/local/lib/python3.12/site-packages/urllib3/connection.py", line 174, in _new_conn
02/17/2024
04:38:55 PM
    conn = connection.create_connection(
02/17/2024
04:38:55 PM
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
02/17/2024
04:38:55 PM
  File "/usr/local/lib/python3.12/site-packages/urllib3/util/connection.py", line 95, in create_connection
02/17/2024
04:38:55 PM
    raise err
02/17/2024
04:38:55 PM
  File "/usr/local/lib/python3.12/site-packages/urllib3/util/connection.py", line 85, in create_connection
02/17/2024
04:38:55 PM
    sock.connect(sa)
02/17/2024
04:38:55 PM
OSError: [Errno 113] Host is unreachable

My battery had gotten a new IP - so it should be fixed soon - thanks!
