### ISSUE TITLE
Integration doesn’t update entities

### ISSUE THREAD

**Issue by LoopCrack** [weltmeyer/ha_sonnenbatterie#65]
Hello,

i have a Sonnenbatterie 10 with version 1.14.5.3041727.
After the Last update of my battery, the integration doesn’t fetch new data in the given interval.
It fetches once after HA boot and after a reconfigure, but not automatically.

Last and only log entry:

```
2024-08-29 22:19:40.389 WARNING (MainThread) [custom_components.sonnenbatterie] Battery:
{'measurements': {'alarms': {'communicationerror': 0, 'highestoperationtemperature': 0, 'initializeerror': 0, 'lowestoperationtemperature': 0, 'lowvoltage': 0, 'mixedbmsmodules': 0, 'modulecorrupted': 0, 'overchargecurrent': 0, 'overdischarge': 0, 'overdischargecurrent': 0, 'oversystemchargecurrentlimit': 0, 'oversystemdischargecurrentlimit': 0, 'overtemperaturecharge': 0, 'overtemperaturedischarge': 0, 'overvoltage': 0, 'undertemperaturecharge': 0, 'undertemperaturedischarge': 0, 'wrongbmstype': 0}, 'battery_status': {'balancechargerequest': '0', 'chargecurrentlimit': '39.970', 'cyclecount': '658', 'dischargecurrentlimit': '39.970', 'fullchargecapacity': '96.678', 'fullchargecapacitywh': '9899.827', 'maximumcelltemperature': '29.95', 'maximumcellvoltage': '3.312', 'maximumcellvoltagenum': '0', 'maximummodulecurrent': '-2.480', 'maximummoduledcvoltage': '105.970', 'maximummoduletemperature': '-273.15', 'minimumcelltemperature': '26.95', 'minimumcellvoltage': '3.310', 'minimumcellvoltagenum': '0', 'minimummodulecurrent': '-2.560', 'minimummoduledcvoltage': '105.960', 'minimummoduletemperature': '-273.15', 'nominalmoduledcvoltage': '102.400', 'relativestateofcharge': '80.0', 'remainingcapacity': '77.342', 'stateofhealth': '99.0', 'systemalarm': '0', 'systemaveragecurrent': '-2.520', 'systemcurrent': '-2.520', 'systemdcvoltage': '211.930', 'systemstatus': '49', 'systemtime': '0', 'systemwarning': '0', 'usableremainingcapacity': '69.608'}, 'battery_status_units': {'balancechargerequest': '', 'chargecurrentlimit': 'A', 'cyclecount': 'count', 'dischargecurrentlimit': 'A', 'fullchargecapacity': 'Ah', 'fullchargecapacitywh': 'Wh', 'maximumcelltemperature': 'C', 'maximumcellvoltage': 'V', 'maximumcellvoltagenum': '', 'maximummodulecurrent': 'A', 'maximummoduledcvoltage': 'V', 'maximummoduletemperature': 'C', 'minimumcelltemperature': 'C', 'minimumcellvoltage': 'V', 'minimumcellvoltagenum': '', 'minimummodulecurrent': 'A', 'minimummoduledcvoltage': 'V', 'minimummoduletemperature': 'C', 'nominalmoduledcvoltage': 'V', 'relativestateofcharge': '%', 'remainingcapacity': 'Ah', 'stateofhealth': '%', 'systemalarm': '', 'systemcurrent': 'A', 'systemdcvoltage': 'V', 'systemstatus': '', 'systemtime': 'sec', 'systemwarning': '', 'usableremainingcapacity': 'Ah'}, 'system_status': {'savedatacompleteflag': 1, 'systemalarmstatus': 0, 'systempoweroffready': 1, 'systemready': 1, 'systemwarningstatus': 0}, 'warnings': {'communicationerror': 0, 'fullchargerequestformaintenance': 0, 'loginfailure': 0, 'mixedbmsmodules': 0, 'modulecorrupted': 0, 'notallserialnumbersread': 0, 'overchargecurrent': 0, 'overdischarge': 0, 'overdischargecurrent': 0, 'overtemperaturebalancer': 0, 'overtemperaturecharge': 0, 'overtemperaturedischarge': 0, 'overtemperaturepcb': 0, 'overvoltage': 0, 'undercurrent': 0, 'undertemperaturecharge': 0, 'undertemperaturedischarge': 0, 'undervoltage': 0, 'wrongbmstype': 0, 'wrongserialnumberformat': 0}}, 'module_log': {'1': {'ModuleAlarm': {'cellunbalance': 'NO ERROR', 'overchargecurrent': 'NO ERROR', 'overdischargecurrent': 'NO ERROR', 'overtemperaturecharge': 'NO ERROR', 'overtemperaturedischarge': 'NO ERROR', 'overvoltage': 'NO ERROR', 'reserved1': 'NO ERROR', 'reserved2': 'NO ERROR', 'undertemperaturecharge': 'NO ERROR', 'undertemperaturedischarge': 'NO ERROR', 'undervoltage': 'NO ERROR'}, 'Module_Data': {'celladdress': '1', 'electricalserialnumber': '137380308', 'electricalversion': '3', 'parameterversion': '2.6.4', 'serialnumber': '400007106120296354', 'softwareversion': '2.8.21', 'systemtime': '0', 'vendorname': 'sonnenModule 4'}, 'Module_Status': {'averagecurrent': '-3070', 'chargecurrentlimit': '39970', 'current': '-3070', 'cyclecount': '658', 'dcvoltage': '105940', 'dischargecurrentlimit': '39970', 'fullchargecapacity': '48339', 'maximumcelltemperature': '3031', 'maximumcellvoltage': '3312', 'minimumcelltemperature': '3011', 'minimumcellvoltage': '3309', 'relativestateofcharge': '800', 'remainingcapacity': '38671', 'stateofhealth': '990'}, 'VendorSpecificError': {'afe_balancer_temp_high': False, 'afe_overcurrent': False, 'afe_overtemperature': False, 'afe_overvoltage': False, 'afe_pcb_temp_high': False, 'afe_selftesterror': '0x0000', 'afe_undercurrent': False, 'afe_undertemperature': False, 'afe_undervoltage': False, 'balancer_temp_high': False, 'mcu_error_afe_driver_error': False, 'mcu_error_app_icm_incompatible': False, 'mcu_error_flow_control_error': False, 'mcu_error_histogram_error': False, 'mcu_error_invalid_parameter_ver': False, 'mcu_error_limit_error': False, 'mcu_error_master_hearbeat_timeout': False, 'mcu_error_no_parameter_block': False, 'mcu_error_param_icm_incompatible': False, 'mcu_error_permanent_error': False, 'mcu_error_safety_line_test_fail': False, 'mcu_error_safety_line_timeout': False, 'mcu_error_safety_line_voltage_low': False, 'mcu_error_soh_too_low': False, 'mcu_error_too_many_limits': False, 'overcurrent': False, 'overtemperature': False, 'overvoltage': False, 'pcb_temp_high': False, 'permanent_balancer_temp_high': False, 'permanent_overcurrent': False, 'permanent_overtemperature': False, 'permanent_overvoltage': False, 'permanent_pcb_temp_high': False, 'permanent_undercurrent': False, 'permanent_undertemperature': False, 'permanent_undervoltage': False, 'undercurrent': False, 'undertemperature': False, 'undervoltage': False}, 'VendorSpecificStatus': {'balancingactive': False, 'charging': False, 'deratingactive': False, 'discharging': True, 'erroractive': 'NO ERROR', 'statusrl': 'CLOSED', 'statusrlcountdown': '8737', 'tricklechargereq': False}, 'VendorSpecificWarning': {'balancer_temp_high': False, 'overcurrent': False, 'overtemperature': False, 'overvoltage': False, 'pcb_temp_high': False, 'undercurrent': False, 'undertemperature': False, 'undervoltage': False}}, '2': {'ModuleAlarm': {'cellunbalance': 'NO ERROR', 'overchargecurrent': 'NO ERROR', 'overdischargecurrent': 'NO ERROR', 'overtemperaturecharge': 'NO ERROR', 'overtemperaturedischarge': 'NO ERROR', 'overvoltage': 'NO ERROR', 'reserved1': 'NO ERROR', 'reserved2': 'NO ERROR', 'undertemperaturecharge': 'NO ERROR', 'undertemperaturedischarge': 'NO ERROR', 'undervoltage': 'NO ERROR'}, 'Module_Data': {'celladdress': '2', 'electricalserialnumber': '137381001', 'electricalversion': '3', 'parameterversion': '2.6.4', 'serialnumber': '400007106120296353', 'softwareversion': '2.8.21', 'systemtime': '0', 'vendorname': 'sonnenModule 4'}, 'Module_Status': {'averagecurrent': '-3050', 'chargecurrentlimit': '39970', 'current': '-3050', 'cyclecount': '647', 'dcvoltage': '105940', 'dischargecurrentlimit': '39970', 'fullchargecapacity': '48339', 'maximumcelltemperature': '3011', 'maximumcellvoltage': '3312', 'minimumcelltemperature': '3001', 'minimumcellvoltage': '3309', 'relativestateofcharge': '800', 'remainingcapacity': '38671', 'stateofhealth': '990'}, 'VendorSpecificError': {'afe_balancer_temp_high': False, 'afe_overcurrent': False, 'afe_overtemperature': False, 'afe_overvoltage': False, 'afe_pcb_temp_high': False, 'afe_selftesterror': '0x0000', 'afe_undercurrent': False, 'afe_undertemperature': False, 'afe_undervoltage': False, 'balancer_temp_high': False, 'mcu_error_afe_driver_error': False, 'mcu_error_app_icm_incompatible': False, 'mcu_error_flow_control_error': False, 'mcu_error_histogram_error': False, 'mcu_error_invalid_parameter_ver': False, 'mcu_error_limit_error': False, 'mcu_error_master_hearbeat_timeout': False, 'mcu_error_no_parameter_block': False, 'mcu_error_param_icm_incompatible': False, 'mcu_error_permanent_error': False, 'mcu_error_safety_line_test_fail': False, 'mcu_error_safety_line_timeout': False, 'mcu_error_safety_line_voltage_low': False, 'mcu_error_soh_too_low': False, 'mcu_error_too_many_limits': False, 'overcurrent': False, 'overtemperature': False, 'overvoltage': False, 'pcb_temp_high': False, 'permanent_balancer_temp_high': False, 'permanent_overcurrent': False, 'permanent_overtemperature': False, 'permanent_overvoltage': False, 'permanent_pcb_temp_high': False, 'permanent_undercurrent': False, 'permanent_undertemperature': False, 'permanent_undervoltage': False, 'undercurrent': False, 'undertemperature': False, 'undervoltage': False}, 'VendorSpecificStatus': {'balancingactive': False, 'charging': False, 'deratingactive': False, 'discharging': True, 'erroractive': 'NO ERROR', 'statusrl': 'CLOSED', 'statusrlcountdown': '8737', 'tricklechargereq': False}, 'VendorSpecificWarning': {'balancer_temp_high': False, 'overcurrent': False, 'overtemperature': False, 'overvoltage': False, 'pcb_temp_high': False, 'undercurrent': False, 'undertemperature': False, 'undervoltage': False}}}, 'show_refresh': True, 'module_refresh_running': False}
```

**Comment by weltmeyer** [comment]
Do you have the latest Version of the integration installed?
![Screenshot_20240830-080316](https://github.com/user-attachments/assets/29fca2fb-f915-4532-9535-0d46c0393ae1)

**Comment by LoopCrack** [comment]
YesMit freundlichen GrüßenThomas MühlAm 30.08.2024 um 08:04 schrieb Jan Weltmeyer ***@***.***>:﻿
Do you have the latest Version of the integration installed?
Screenshot_20240830-080316.png (view on web)

**Comment by Corubs** [comment]
Same problem here

- sonnenbatterie_XXX_meter_production_4_1_w_tot- al
- sensor.sonnenbatterie_XXX_meter_consumption_4_2_w_total

And others are not available.

Not all, but many.

**Comment by weltmeyer** [comment]
So if you are messing the diagnostic sensors, it may be because sonnen changed the IDs of the meters.
Try to look if there are disabled sensors with new IDs.

for me as an example
"sonnenbatterie_107700_meter_production_4_1_w_l3" changed to
"sonnenbatterie_107700_meter_production_0_1_w_l3"

as the deviceId move to 0 instead of 4

**Comment by matthiasblomme** [comment]
Lost all info from sonnen battery. Reinstalled the integration, removed it completely and after adding it I have 0 entities

![image](https://github.com/user-attachments/assets/380e8a35-f190-46fa-99be-f4779bdcaeea)


I also have these log errors:
2024-09-03 19:27:21.148 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing platform custom_components.sonnenbatterie.sensor
2024-09-03 19:27:21.158 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform sonnenbatterie.sensor: Platform not found (Exception importing custom_components.sonnenbatterie.sensor).
2024-09-03 19:45:32.530 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing platform custom_components.sonnenbatterie.sensor
2024-09-03 19:45:32.537 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform sonnenbatterie.sensor: Platform not found (Exception importing custom_components.sonnenbatterie.sensor).
2024-09-03 19:45:44.669 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing platform custom_components.sonnenbatterie.sensor
2024-09-03 19:45:44.672 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform sonnenbatterie.sensor: Platform not found (Exception importing custom_components.sonnenbatterie.sensor).
2024-09-03 19:47:32.287 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing platform custom_components.sonnenbatterie.sensor
2024-09-03 19:47:32.292 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform sonnenbatterie.sensor: Platform not found (Exception importing custom_components.sonnenbatterie.sensor).
2024-09-03 19:47:32.303 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing platform custom_components.sonnenbatterie.sensor
2024-09-03 19:47:32.309 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform sonnenbatterie.sensor: Platform not found (Exception importing custom_components.sonnenbatterie.sensor).
2024-09-03 19:50:45.145 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing platform custom_components.sonnenbatterie.sensor
2024-09-03 19:50:45.151 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform sonnenbatterie.sensor: Platform not found (Exception importing custom_components.sonnenbatterie.sensor).

**Comment by Beecky2001** [comment]
@matthiasblomme, I had the same issue. After removing and reinstalling all entities were gone.
I could fix it by adding "weltmeyer/ha_sonnenbatterie" as a custom repository in HACS. 
From this point I could download the Sonnenbattery intgration again and all is working fine now

**Comment by matthiasblomme** [comment]
@Beecky2001 
Removed everything, including the repo. Added it again as custom repo, added the integration again but still nothing
![image](https://github.com/user-attachments/assets/da3ee6a8-9d14-491e-b2aa-56b16d7360b7)

This error originated from a custom integration.

Logger: homeassistant.loader
Source: custom_components/sonnenbatterie/sensor_list.py:14
Integration: Sonnenbatterie (documentation)
First occurred: 09:12:47 (2 occurrences)
Last logged: 09:13:01

Unexpected exception importing platform custom_components.sonnenbatterie.sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 833, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 850, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/sonnenbatterie/sensor.py", line 22, in <module>
    from .sensor_list import (
  File "/config/custom_components/sonnenbatterie/sensor_list.py", line 14, in <module>
    class SonnenbatterieSensorEntityDescription(SensorEntityDescription):
  File "/usr/local/lib/python3.10/dataclasses.py", line 1175, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
  File "/usr/local/lib/python3.10/dataclasses.py", line 990, in _process_class
    raise TypeError('cannot inherit frozen dataclass from a '
TypeError: cannot inherit frozen dataclass from a non-frozen one

**Comment by RustyDust** [comment]
> Unexpected exception importing platform custom_components.sonnenbatterie.sensor Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/loader.py", line 833, in get_platform cache[full_name] = self._import_platform(platform_name) File "/usr/src/homeassistant/homeassistant/loader.py", line 850, in _import_platform return importlib.import_module(f"{self.pkg_path}.{platform_name}") File "/usr/local/lib/python3.10/importlib/**init**.py", line 126, in import_module return _bootstrap._gcd_import(name[level:], package, level) File "", line 1050, in _gcd_import File "", line 1027, in _find_and_load File "", line 1006, in _find_and_load_unlocked File "", line 688, in _load_unlocked File "", line 883, in exec_module File "", line 241, in _call_with_frames_removed File "/config/custom_components/sonnenbatterie/sensor.py", line 22, in from .sensor_list import ( File "/config/custom_components/sonnenbatterie/sensor_list.py", line 14, in class SonnenbatterieSensorEntityDescription(SensorEntityDescription): **File "/usr/local/lib/python3.10/dataclasses.py",** line 1175, in wrap return _process_class(cls, init, repr, eq, order, unsafe_hash, **File "/usr/local/lib/python3.10/dataclasses.py",** line 990, in _process_class raise TypeError('cannot inherit frozen dataclass from a ' TypeError: cannot inherit frozen dataclass from a non-frozen one

It looks like you're running on Python 3.10 which is no longer supported by HomeAssistant. Try upgrading to 3.12 and see whether this fixes the problem.

**Comment by whiteman7** [comment]
Hello, has there been any progress with the production IDs?
Despite updates (including Python) I still have problems with 

sensor.sonnenbatterie_xxx_meter_production_1_1_w_l3 (...l2 / l1)...
... 1_1_total is missing
sensor.sonnenbatterie_xxx_meter_production_0_2_w_total

send zero values. The actual overall production is only delivered via ...procuction_w.

thx

**Comment by RustyDust** [comment]
> Hello, has there been any progress with the production IDs? Despite updates (including Python) I still have problems with
> 
> sensor.sonnenbatterie_xxx_meter_production_1_1_w_l3 (...l2 / l1)... ... 1_1_total is missing sensor.sonnenbatterie_xxx_meter_production_0_2_w_total
> 
> send zero values. The actual overall production is only delivered via ...procuction_w.
> 
> thx

As mentioned [here](https://github.com/weltmeyer/ha_sonnenbatterie/issues/65#issuecomment-2323264650) Sonnen changed the IDs of some of the meters. Since the integration creates the sensor names based on the meter IDs returned by the Sonnen API, the names most likely have changed for you like this:

`sensor.(...)_meter_production_1_1_w_lx` -> ` sensor.(...)_meter_production_0_1_w_lx`
`sensor.(...)_meter_production_1_1_total` -> `sensor.(...)_meter_production_0_1_w_total`

The best thing to do would be to go to the integration via "Settings -> Devices & Services -> SonnenBatterie -> Entities" and check for those listed as "unavailable" as well as new ones that are currently in a disabled state. Enable the disabled ones and take note of which of the now unavailable ones they probably replace.

If you have any helpers defined using the no longer provided sensors you'll have to update or recreate those using the new values. I know this can be a bit of work but again: this is **not** the integration's fault but was caused by the recent and unannounced change to the IDs made by Sonnen.

**Comment by whiteman7** [comment]
Many thanks for your input. I have seen and checked the changed ID of sonnen. As already mentioned, I only have these four entities xxx_procuction_xxx which output null values. Deactivated or inactive entities do not appear for me. I cannot find any entities that provide W values, with the exception of xxx_procuction_w ...

**Comment by RustyDust** [comment]
Could you please do [this](https://github.com/weltmeyer/ha_sonnenbatterie?tab=readme-ov-file#unusedunavailable-sensors) and send the log output it produces?

**Comment by whiteman7** [comment]
Hello, please find enclosed the log file. Many thanks for your suggestions, lg

**Comment by whiteman7** [comment]
Hello, please find enclosed the log file. Many thanks for your suggestions, lg

[home-assistant_sonnenbatterie_2024-09-12.log](https://github.com/user-attachments/files/16983149/home-assistant_sonnenbatterie_2024-09-12.log)

**Comment by RustyDust** [comment]
Unfortunately the log output doesn't say much :(
Can you please use [this tool](https://github.com/RustyDust/sb_info/releases) and send the output from that (**make sure to strip the password first**)?

**Comment by whiteman7** [comment]
Hi, thank you very much for the script. 
A production is reported in area “0”. “1” returns zero values. The entity is stored with xx1_1_w_l1 in ha... lg

[Log_sb_info.txt](https://github.com/user-attachments/files/16997777/Log_sb_info.txt)

**Comment by RustyDust** [comment]
Ok, ich hab' mir das jetzt angesehen. Die Werte sind alle da, sehen zwar etwas anders aus als bei meiner SB 10, aber im großen und ganzen passt alles. Vielleicht verstehe ich einfach nicht richtig, was das Problem ist. Bei mir sind auch einige Werte immer 0. Ist halt das, was die API der SB liefert. Was genau möchtest du denn machen, vielleicht finden wir dann den passenden Sensor für dich ;)

**Comment by weltmeyer** [comment]
All values ​​are 0 on power meter 1,
this also reports error 3...I don't know what that means:
<img width="314" alt="image" src="https://github.com/user-attachments/assets/429906d7-b6c7-40a9-b322-c665e8dd3552">

**Comment by weltmeyer** [comment]
Having Voltage displayed but no current could point to a failure in the sensor.

**Comment by whiteman7** [comment]
@RustyDust - in meinem HA werden "nur" die Entitäten zu sensor.sonnenbatterie_xyz_meter_production_1_1_w_l1 angezeigt, die 0-Werte liefern. Die Entitäten mit  ...0_1_w_l1 etc existieren nicht, die aber die Werte liefern würden. Kann ich diese in sonnenbatterie fehlende Entität in HA überhaupt anlegen? LG

**Comment by RustyDust** [comment]
Ich fürchte, da werden wir auf die Schnelle nichts machen können, da das Problem tatsächlich an den Antworten deiner SB liegt. Wenn du mal in deinem Log auf die Ausgabe von "Power meter" schaust, dann siehst du, dass die Werte unter `"0"` alle für "consumption" (siehe Feld `"direction"` sind, also "Verbrauch". Deswegen werden da natürlich  keine "production"-Sensoren erzeugt.
Unter `"1"`wären die Werte für "production", für die werden ja auch Sensoren angelegt. Nur dass bei dir halt `w_total` immer "0" ist. Wie @weltmeyer  oben schon angedeutet hat: der Wert "3" beim Feld `"error"` deutet auf einen Fehler bei deiner SB hin.
Du kannst mal versuchen, die SB nach Anleitung neu zu starten, wenn das nichts hilft müsstest du vermutlich den Service kontaktieren.

**Comment by whiteman7** [comment]
HI, habe die Anlage neu gestartet und die Auswertung nochmal durchgeführt. Gleiche Fehlermeldung. Habe dann die Firma direkt angeschrieben und die File übermittelt:

Antwort: Ich habe Ihre sonnenBatterie überprüft und keine Fehler festgestellt. Die von Ihnen beschriebene Fehlermeldung erscheint, weil bei Ihrer sonnenBatterie Eco 8.1 Hybrid die Klappstromwandler für die Erzeugung konfiguriert werden aber nicht angeschlossen sind. Die Erzeugung wird direkt über Ihren internen Wechselrichter erfasst. Diese Fehlermeldung kann ignoriert werden da sie nicht relevant ist.

Auf Nachfrage wurde mir eine Anleitung für API (v1) übermittelt...

**Comment by RustyDust** [comment]
> Antwort: (...). Die Erzeugung wird direkt über Ihren internen Wechselrichter erfasst. 
> (...)
> Auf Nachfrage wurde mir eine Anleitung für API (v1) übermittelt...

Toll, was für Helden. Dann frag' mal nach, **wo** du denn dann genau im Output der API die gesamte produzierte Leistung auslesen kannst. Ich finde da nichts.

**Comment by RustyDust** [comment]
Hast du mal nachgesehen, was die API v2 für Daten liefert? Das kannst du direkt im Web-Interface der SB machen.

**Comment by whiteman7** [comment]
Habe heute den ganzen Tag über mich damit beschäftigt, im Webinterface (Webhook APi) werden NUR Fehlermeldungen produziert. In der Kommandozeile geht NUR v1 mit Status (latestdata, powermeter etc nur Fehler). In meiner yaml hatte ich v2 programmiert, keine Werte mehr.

Die Gesamt-Produktion wird bei v1 status mit produce_w schon gemeldet, aber L1-3 und W Gesamt nicht.

Werde Morgen nochmal ne höfliche Mail an die Fa Sonnen schreiben. Mal schauen… thx für eure Hilfe, lg

**Comment by RustyDust** [comment]
> Habe heute den ganzen Tag über mich damit beschäftigt, im Webinterface (Webhook APi) werden NUR Fehlermeldungen produziert.

Bei der Webhook-API bist du eh falsch. Wenn du im Web-Interface angemeldet bist, dann gehst du zu "Software-Integration". Dort wird dir unter "Read API" und "Write API" entweder schon ein Token angezeigt oder du generierst halt schnell eines mit Klick auf "Neues Erstellen". Das Token kopierst du dir in die Zwischenablage (oder einen Texteditor ...) und klickst dann auf den Link unter dem Token namens "sonnenBatterie JSON API v2 Dokumentation".
Da siehst du dann die einzelnen v2 API-Calls und eine (ziemlich schlechte) Anleitung, wie die zu benutzen sind.

Um z.B. die gesamte Config der SB zu bekommen wäre der Befehl

`curl --header 'Auth-Token: <das kopierte Token>' http://<IP der SB>/api/v2/configurations`

**Aber:** selbst mit der API v2 liefert zumindest meine SB keinen Wert für die Gesamtmenge der produzierten Energie.

**Comment by whiteman7** [comment]
Danke für die ausführliche Info... habe am Sonntag eine entsprechende Mail an die Firma übermittelt, heute sind die "Produktionswerte" auf allen Längen "inaktiv" bzw werden nicht mehr angezeigt. Weder HA noch via curl... scheint so als ob die an der Software basteln (v 1.14.5, Web-Interface). Bin da mal gespannt ;-)

**Comment by RustyDust** [comment]
Closing as stale, feel free to reopen if there#s new information or new developments.

**Comment by RustyDust** [comment]
@whiteman7 
Ich glaube, ich habe per Zufall dein Problem endlich verstanden und hoffentlich auch gelöst.
Ursache waren wohl zwei Dinge, die unglücklich zusammengepsielt haben:
1) In den Dateien mit den Übersetzungseinträgen war ein falscher Eintrag für die aktuelle Strom-Produktion der Sonnenbatterie. Deswegen wurde der immer als "sonnenbatterie unknown" angezeigt.
2) Mit dem großen Rewrite der Integration durch @Xitee1 hat sich auch der Name des Sensors gewändert. Der hiess früher `xxx_production_w` und heisst jetzt `xxx_state_production`. Wenn du also die Integration mal gelöscht und neu installiert hast, dann _gibt es keinen Sensor "xxx_production_w" mehr_, seine Aufgabe übernimmt jetzt "xxx_state_production"

Entsprechend müssen natürlich auch alle anderen Sachen, die den alten Sensor verwendet hatten auf den neuen umgestellt werden. Sorry dafür.

Leider ist mit beides beim Testen damals nicht aufgefallen, da vorhandene Sensoren einfach weiter funktionieren. Das Problem tritt tatsächlich nur bei einer Neu-Installation auf (denke ich). Sollte die nächste Version der Integration dein Problem nicht beheben, dann mach' bitte ein neues Issue auf, dann schaue ich da nochmal genauer rein.
