### ISSUE TITLE
Unauthorized for url: http://192.168.10.209/api/session

### ISSUE THREAD

**Issue by emign** [weltmeyer/ha_sonnenbatterie#8]
Hey,

I try to set this up with my ECO 8 but I cannot even login. The password is def. correct (see GIF). I also tried "User" as user, but that offers the same result

![screencast 2021-10-17 21-19-13](https://user-images.githubusercontent.com/5278352/137641867-9fac2c71-fb85-4a90-8278-85e9f4fddcdf.gif)

```
This error originated from a custom integration.

Logger: custom_components.sonnenbatterie
Source: custom_components/sonnenbatterie/config_flow.py:50 
Integration: sonnenbatterie (documentation) 
First occurred: 9:02:06 PM (6 occurrences) 
Last logged: 9:12:53 PM

Unable to connect to sonnenbatterie: Traceback (most recent call last): File "/config/custom_components/sonnenbatterie/config_flow.py", line 42, in async_step_user sonnenInst=await self.hass.async_add_executor_job(_internal_setup,username,password,ipaddress); File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run result = self.fn(*self.args, **self.kwargs) File "/config/custom_components/sonnenbatterie/config_flow.py", line 41, in _internal_setup return sonnenbatterie(_username,_password,_ipaddress) File "/usr/local/lib/python3.9/site-packages/sonnenbatterie/sonnenbatterie.py", line 10, in __init__ self._login() File "/usr/local/lib/python3.9/site-packages/sonnenbatterie/sonnenbatterie.py", line 24, in _login getsession.raise_for_status() File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 953, in raise_for_status raise HTTPError(http_error_msg, response=self) requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: http://192.168.10.209/api/session
```

**Comment by emign** [comment]
That works. But only shows a subset of relevant values. The installer password is the same for all too I think
